### ISSUE TITLE
downloader.js isnt working

### ISSUE THREAD

**Issue by baezahuertaelias** [stanimirovv/volafile-scrapper#1]
Hi, I was trying to run the script but there's an error.
Hope you can fix it. Thx

```
/home/pi/volafile-scrapper/downloader.js:97
      const { statusCode } = res;
            ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by stanimirovv** [comment]
@baezahuertaelias hey, can you please give me the full command you were running ?

**Comment by baezahuertaelias** [comment]
@stanimirovv This is the command
```
phantomjs scrapper.js chile | node downloader.js weavola
```

**Comment by stanimirovv** [comment]
@baezahuertaelias thanks, I will have a look at it and get back to you.

**Comment by baezahuertaelias** [comment]
@stanimirovv Ok! I'll be waiting. Thanks (:

**Comment by stanimirovv** [comment]
@baezahuertaelias  Hm... I ran the command successfully. Did you run ```npm install``` after checking out the repo ? 

Also, can you please give me your node version ? ```node --version``` I am running v8.1.3

**Comment by baezahuertaelias** [comment]
First I've cloned the repo, after ```sudo npm install -g phantomjs``` and finally run the command
I'm using MacOS High Sierra, node v4.4.5 and npm v2.15.5.

Also I've tried in a Raspberry Pi 3, and it shows the same error

**Comment by stanimirovv** [comment]
I would wager it's the version of nodejs/npm. ```const``` was added in ES6, I doubt node 4.4.5 supports it, pleas give it a try after updating the version.

Should be something along the lines of:
```
brew update
brew upgrade node
npm install -g npm
```

One last thing - I am not sure if ```sudo npm install -g phantomjs``` has installed *all* the modules in ```package.json```. This isn't related to the current problem, but once the version of node is upgraded if there is a missing module you will get another error.

**Comment by baezahuertaelias** [comment]
@stanimirovv Now I can use it. The problem was node version, also it needs to install node packages ```get-stdin``` and ```cheerio``` to work properly.

**Comment by stanimirovv** [comment]
Great, I am happy you got it working.

In a few days I will package the entire project in a docker file to make running it easier. ( so you don't have to manually install packages and handle the node version).
